basePath: /api
definitions:
  bananas:
    properties:
      color:
        title: Name
        type: string
      name:
        title: Name
        type: string
    required:
    - name
    type: object
  error:
    properties:
      details:
        description: more details about the error.
        type: object
      error:
        description: Title of the error
        type: string
    type: object
info:
  description: These APIs let you interact with projects by arannou
  title: Arannou backend
  version: local
paths:
  /schema:
    get:
      description: Swagger schema is the whole application data model. Respecting
        Swagger openapi reference.
      responses:
        '200':
          description: Swagger schema for the application
      summary: Get swagger schema
      tags:
      - Diverse
  /upload-image:
    post:
      consumes:
      - multipart/form-data
      description: Import a picture like jpeg, gif, png...
      parameters:
      - description: Image file
        in: formData
        name: image
        required: true
        type: file
      responses:
        '200':
          description: Image imported
        '400':
          description: Bad request. Overview message and detailed informations
          schema:
            $ref: '#/definitions/error'
      summary: Import a image
  /{object_type}:
    get:
      parameters:
      - description: Object type
        in: path
        name: object_type
        required: true
        type: string
      responses:
        '200':
          description: List of objects
          schema:
            type: object
      summary: Get all object of object_type
    post:
      parameters:
      - description: Object type
        in: path
        name: object_type
        required: true
        type: string
      - description: Well formed model object
        in: body
        name: Object body
        required: true
        schema:
          type: object
      responses:
        '201':
          description: Object added. The responses contains the new created object
            as it might have new properties added by back end
        '400':
          description: Bad request. Overview message and detailed informations
          schema:
            $ref: '#/definitions/error'
      summary: Add a new object_type
  /{object_type}/{name}:
    delete:
      parameters:
      - description: Object type
        in: path
        name: object_type
        required: true
        type: string
      - description: Object name
        in: path
        name: name
        required: true
        type: string
      responses:
        '201':
          description: Object deleted
        '400':
          description: Bad request. Overview message and detailed informations
          schema:
            $ref: '#/definitions/error'
      summary: Delete an object of object_type
    put:
      parameters:
      - description: Object type
        in: path
        name: object_type
        required: true
        type: string
      - description: Object name
        in: path
        name: name
        required: true
        type: string
      - description: New object containing your modifications
        in: body
        name: Object body
        required: true
        schema:
          type: object
      responses:
        '201':
          description: Object updated
        '400':
          description: Bad request. Overview message and detailed informations
          schema:
            $ref: '#/definitions/error'
      summary: Update an object of object_type
swagger: '2.0'
